version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  reviewers:
  - grrakesh4769
  assignees:
  - grrakesh4769
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: ember-template-lint
    versions:
    - 2.18.0
    - 2.18.1
    - 2.19.0
    - 2.20.0
    - 3.0.0
    - 3.0.1
    - 3.1.1
    - 3.2.0
  - dependency-name: atom-package-deps
    versions:
    - 7.1.0
    - 7.2.0
    - 7.2.1
    - 7.2.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
